highlighter: pygments
permalink: /:year/:month/:day/:title
exclude:
    - Gemfile
    - Gemfile.lock
    - package.json
    - init.sh
include:
    - .htaccess

host: 127.0.0.1
port: 8001

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
